### ISSUE TITLE
Issue when some is creating a title for the notes

### ISSUE THREAD

**Issue by MrMaina100** [StanleyMasinde/notes#31]
![image](https://github.com/StanleyMasinde/notes/assets/91890976/99fb9fe1-e0e9-4084-af8c-3f31462a8ba6)

I think it would be nice  when someone  finishes creating a title for the notes  should press enter for the title to be save and go to the next line to start creating the notes

**Comment by StanleyMasinde** [comment]
Thank you for the suggestion @MrMaina100, I'll consider it in the next release
